add Werkzeug version constraint to requirements
Werkzeug >= 3.0 causes `ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.8/dist-packages/werkzeug/urls.py)` in `mediator/brotab_mediator.py`. Flask 2.0.2's requirements specify only Werkzeug >= 2.0 but should also specify Werkzeug < 3.0. Unless and until this is fixed upstream, clients of Flask 2.0.2 must specify Werkzeug < 3.0 themselves to avoid this error.